In [70]:
# Installations for the project
%pip install requests
%pip install pandas
%pip install numpy

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [8]:
import requests
print(requests.__version__)
import pandas as pd
print(pd.__version__)
import numpy as np
print(np.__version__)
import re
print(re.__version__)

2.31.0
2.2.2
1.26.4
2.2.1


# Basics


In [68]:
print(np)

<module 'numpy' from '/Users/ap/Repositories/github/numbers-training/.conda/lib/python3.11/site-packages/numpy/__init__.py'>


In [69]:
x =  np.arange(1,9) ** 4
print(x)
print(type(x))

[   1   16   81  256  625 1296 2401 4096]
<class 'numpy.ndarray'>


In [70]:
l = []
for i in range(1,5):
  int_1 = input("Enter a number: ")
  l.append(int_1)
  
y=  np.array(l)
print(y.ndim)

1


In [71]:
ar2 = np.array([[1,2,3, 4], [4,5,6, 10]])
print(ar2)

[[ 1  2  3  4]
 [ 4  5  6 10]]


In [72]:
arn = np.array([1,2,3,4], ndmin=10)
print(arn)

[[[[[[[[[[1 2 3 4]]]]]]]]]]


## Zeros


In [73]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones


In [74]:
ar_one = np.ones(4)

print(ar_one)
print()
ar_one1 = np.ones((3,4))
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Range


In [75]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


## Diagonal


In [76]:
ar_dia = np.eye(4)
print(ar_dia)

print()

ar_dia2 = np.eye(4,5)
print(ar_dia2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


## Linespace


In [77]:
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)
ar_lin2 = np.linspace(0,20,num=6)
print(ar_lin2)

[ 0.   2.5  5.   7.5 10. ]
[ 0.  4.  8. 12. 16. 20.]


## Functions


### Random


In [78]:
arr_r = np.random.rand(4)
print(arr_r)

[0.85619029 0.96987374 0.27191725 0.57642632]


In [79]:
var_1 = np.random.rand(2,5)
print(var_1)

[[0.79378965 0.60725856 0.23001451 0.39325752 0.47088105]
 [0.33972066 0.21657806 0.95536001 0.54593686 0.6274448 ]]


### randn()


In [81]:
var_2 = np.random.randn(5)
print(var_2)

[-0.00619686 -0.84589411  2.28639379 -0.01146199 -0.23532768]


### randf()


In [83]:
var_3 = np.random.ranf(5)
print(var_3)

[0.80618107 0.37647937 0.32745194 0.02701013 0.58346463]


## randint


In [97]:
var_4 = np.array([1.213321,2,3,'A'])
print('Data type: ', var_4.dtype)

Data type:  <U32


## Convert datatype


In [111]:
x = np.array([1,2,3,4, 127], dtype=np.int8)
print("Data Type : ",x.dtype)


Data Type :  int8


## Arithmetic operations


In [6]:
my_arr1 = np.array([1,2,3,4])
varadd = my_arr1 + 3




In [17]:
var_21 = np.array([[1,2,3,4],[1,2,3,4]])
print(var_21 % 3)

print()
var_22 = np.array([[1,2,3,4],[1,3,3,5]])
print(var_21 * var_22)
print()
print(var_21 % var_22)

[[1 2 0 1]
 [1 2 0 1]]

[[ 1  4  9 16]
 [ 1  6  9 20]]

[[0 0 0 0]
 [0 2 0 4]]


## Min Max


In [40]:
var_5 = np.array([1,2,3,4])
print(np.max(var_5))
print(np.min(var_5))
print('Index of min:', np.argmin(var_5))
print('Index of max:', np.argmax(var_5))


4
1
Index of min: 0
Index of max: 3


In [51]:
var_6 = np.array([[2,1,3], [9,5,6], [0,123,32]])
print(np.min(var_6, axis=0))
print(np.min(var_6, axis=1))



[0 1 3]
[1 5 0]


## Sin and Cos


In [54]:
var_7 = np.array([1,2,3,4])

print(np.sin(var_7))
print(np.cos(var_7))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


## Cumsum


In [56]:
var_8 = np.array([1,2,3,4])

print(np.cumsum(var_8))

[ 1  3  6 10]


## Shape and Reshape


In [59]:
var_9 = np.array([[1,2,3,4],[1,2,3,4]])
print(var_9.shape)

var_10 = np.array([[1,2],[1,2]])
print(var_10.shape)

var_11 = np.array([1,2,3,4], ndmin=4)
print(var_11.shape)

(2, 4)
(2, 2)
(1, 1, 1, 4)


In [69]:
var_12 = np.array([1,2,3,4,5,6])
print(var_12.reshape(3,2))
print()
print(var_12.reshape(3,2))
print()
print(var_12.reshape(2,3))
print()

x = var_12.reshape(2,3)

# get back 1D array
print(x.reshape(-1))



[[1 2]
 [3 4]
 [5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


# Broadcasting
